# Generated by Django 2.2.2 on 2019-06-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='HeaderModel',
        ),
    ]
