# Generated by Django 2.2.2 on 2019-06-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190628_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='headermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='news/icons/'),
        ),
    ]
