# Generated by Django 2.2.2 on 2019-06-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_headermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headermodel',
            name='dropdown',
        ),
    ]
