# Generated by Django 2.2.2 on 2019-06-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_headermodel_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermodel',
            name='image',
            field=models.ImageField(upload_to='news/icons/'),
        ),
    ]
