# Generated by Django 2.2.2 on 2019-06-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190628_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/icons/'),
        ),
    ]
