# Generated by Django 2.2.2 on 2019-06-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190628_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headermodel',
            name='image',
        ),
    ]
