# Generated by Django 2.2.2 on 2019-06-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190628_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='shor_title',
            new_name='short_title',
        ),
    ]
