# Generated by Django 2.2.2 on 2019-07-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20190630_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullnews',
            name='news_id',
        ),
    ]
