# Generated by Django 2.2.2 on 2019-07-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_fullnews_news_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullNews',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_title',
            new_name='title',
        ),
    ]
