# Generated by Django 2.2.2 on 2019-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190707_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='modal_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
