# Generated by Django 2.2.2 on 2019-07-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_news_modal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
